(function() {    var toc =  [
{"name":"曲げリリーフ(Bend Relief)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Bend_Relief.htm"},
{"name":"ブリッジランス間隔(Bridge Lance Spacing)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Bridge_Lance_Spacing.htm"},
{"name":"押し出し穴付きブリッジランス(Bridge Lance with Extruded Hole)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Bridge_Lance_with_Extruded_Hole.htm"},
{"name":"カードガイド成形と曲げの距離(Card Guide Form to Bend Distance)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Card_Guide_Form_to_Bend_Distance.htm"},
{"name":"カードガイド成形寸法(Card Guide Form Parameters)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Card_Guide_Form_Parameters.htm"},
{"name":"クローズドヘム寸法(Closed Hem Parameters)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Closed_Hem_Parameters.htm"},
{"name":"曲げ付きクローズドヘム寸法(Closed Hem with a Bend Parameters)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Closed_Hem_with_a_Bend_Parameters.htm"},
{"name":"座ぐり穴と部品エッジ距離(Counterbore Hole Distance to Part Edge)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/counterbore_hole_distance_to_part_edge.htm"},
{"name":"座ぐり穴と曲げの距離(Counterbore Hole to Bend Distance)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/counterbore_hole_to_bend_distance.htm"},
{"name":"座ぐり穴間隔(Counterbore Hole Spacing)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/counterbore_hole_spacing.htm"},
{"name":"皿穴と成形形状の距離(Countersink Hole Distance to Form)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Countersink_Hole_Distance_To_Form.htm"},
{"name":"皿穴と部品エッジの距離(Countersink Hole Distance to Part Edge)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/countersink_hole_distance_to_part_edge.htm"},
{"name":"皿穴と曲げの距離(Countersink Hole to Bend Distance)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/countersink_hole_to_bend_distance.htm"},
{"name":"皿穴間隔(Countersink Hole Spacing)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/countersink_hole_spacing.htm"},
{"name":"カールと曲げの距離(Curl Distance to Bends)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Curl_Distance_To_Bends.htm"},
{"name":"カールとカットアウト距離(Curl Distance to Cutouts)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Curl_Distance_To_Cutouts.htm"},
{"name":"カットアウトと部品エッジ距離(Cutout Distance to Part Edge)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/cutout_distance_to_part_edge.htm"},
{"name":"長さに基づくカットアウトと部品エッジ距離(Cutout Distance to Part Edge - Based on Line Length)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/cutout_distance_to_part_edge(LineLengthBased).htm"},
{"name":"カットアウトと曲げの距離(Cutout to Bend Distance)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/cutout_to_bend_distance.htm"},
{"name":"長さに基づくカットアウトと曲げ距離(Cutout to Bend Distance - Based on Line Length)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/cutout_distance_to_bend(LineLengthBased).htm"},
{"name":"カットアウト長さに基づくエッジ距離(Cutout to Part Edge Distance - Based on Cutout Length)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Cutout_to_Part_Edge_Distance.htm"},
{"name":"ダウエルと曲げの距離(Dowel Distance to Bends)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/dowel_distance_to_bends.htm"},
{"name":"ダウエルとカットアウトの距離(Dowel Distance to Cutouts)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/dowel_distance_to_cutouts.htm"},
{"name":"ダウエルと部品エッジの距離(Dowel Distance to Part Edge)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/dowel_distance_to_part_edge.htm"},
{"name":"ダウエル外径(Dowel Outer Diameter)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/dowel_outer_diameter.htm"},
{"name":"ダウエル外径高さ(Dowel Outer Diameter Height)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/dowel_height.htm"},
{"name":"ダウエル間隔(Dowel Spacing)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/dowel_spacing.htm"},
{"name":"エンボスとカットアウト距離(Emboss Distance to Cutouts)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Emboss_to_Cutouts.htm"},
{"name":"エンボスと曲げの距離(Emboss to Bend Distance)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Emboss_To_Bend_Distance.htm"},
{"name":"エンボスと部品エッジの距離(Emboss to Part Edge Distance)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Emboss_To_Edge_Distance.htm"},
{"name":"エンボス間隔(Emboss Spacing)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Emboss_Spacing.htm"},
{"name":"押し出し穴付きエンボス寸法(Emboss with Extruded Hole Parameters)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Emboss_with_Extruded_Hole_Parameters.htm"},
{"name":"押し出し成形とカットアウトの距離(Extruded Form Distance to Cutouts)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Extruded_Form_Distance_To_Cutouts.htm"},
{"name":"押し出し成形と部品エッジ距離(Extruded Form Distance to Part Edge)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Extruded_Form_Distance_To_Part_Edge.htm"},
{"name":"押し出し成形寸法(Extruded Form Parameters)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Extruded_Form_Parameters.htm"},
{"name":"押し出し成形と曲げの距離(Extruded Form to Bend Distance)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Extruded_Form_to_Bend_.htm"},
{"name":"押し出し成形の間隔(Extruded Form Spacing)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Extruded_Form_Spacing.htm"},
{"name":"押し出し穴と曲げの距離(Extruded Hole Distance to Bends)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/burring_hole_distance_to_bends.htm"},
{"name":"押し出し穴とカットアウト距離(Extruded Hole Distance to Cutouts)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/burring_hole_distance_to_cutout.htm"},
{"name":"押し出し穴と部品エッジ距離(Extruded Hole Distance to Part Edge)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/burring_hole_distance_to_part_edge.htm"},
{"name":"押し出し穴高さ(Extruded Hole Height)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/burring_hole_height.htm"},
{"name":"押し出し穴の内径(Extruded Hole Inner Diameter)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/burring_hole_inner_diameter.htm"},
{"name":"押し出し穴パラメータ(Extruded Hole Parameters)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/burring_hole_parameters.htm"},
{"name":"押し出し穴の間隔(Extruded Hole Spacing)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/burring_hole_spacing.htm"},
{"name":"製造方向(フィーチャ)(Feature Direction for Fabrication)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/feature_direction_for_fabrication.htm"},
{"name":"フランジ干渉チェック(Flange Interference Check)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/flange_interference_check.htm"},
{"name":"ガセット寸法(Gusset Parameter)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Gusset_Parameter.htm"},
{"name":"ガセット間隔(Gusset Spacing)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Gusset_Spacing.htm"},
{"name":"ハーフシア寸法(Half-Shear Parameters)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/half_shear_Parameters.htm"},
{"name":"ヘムと曲げ距離(Hem Distance to Bends)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Hem_Distance_To_Bends.htm"},
{"name":"ヘムとカットアウト距離(Hem Distance to Cutouts)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Hem_Distance_To_Cutouts.htm"},
{"name":"ヘムと成形形状の距離(Hem Distance to Form)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Hem_Distance_To_Form.htm"},
{"name":"ヘム間隔(Hem Spacing)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Hem_Spacing.htm"},
{"name":"穴と曲げの距離(Hole Distance to Bends)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/hole_distance_to_bends.htm"},
{"name":"穴と部品エッジ距離(Hole to Part Edge Distance)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/hole_to_part_edge_distance.htm"},
{"name":"フラットパターンの干渉(Interference in Flat Pattern)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/interference_in_flat_pattern.htm"},
{"name":"ナイフエッジ(Knife Edge)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/knife_edge.htm"},
{"name":"ブリッジの最大角度(Maximum Bridge Angle)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/maximum_bridge_angle.htm"},
{"name":"ブリッジの最大高さ(Maximum Bridge Height)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/maximum_bridge_height.htm"},
{"name":"座ぐり穴の最大深さ(Maximum Depth of Counterbore)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/maximum_depth_of_counterbore.htm"},
{"name":"皿穴の最大深さ(Maximum Depth of Countersink)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/maximum_depth_of_countersink.htm"},
{"name":"エンボス最大深さ(Maximum Embossment Depth)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/maximum_embossment_depth.htm"},
{"name":"最小曲げ半径(Minimum Bend Radius)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/minimum_bend_radius.htm"},
{"name":"ブリッジの最小幅(Minimum Bridge Width)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/minimum_bridge_width.htm"},
{"name":"最小コーナー半径(Minimum Corner Radius)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/minimum_corner_radius.htm"},
{"name":"ヘム最小コーナー半径(Minimum Corner Radius for Hem)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/minimum_corner_radius_for_hem.htm"},
{"name":"カットアウト間の最小距離(Minimum Distance between Cutouts)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/min_dist_bet_cutouts.htm"},
{"name":"カットアウト間距離(Minimum Distance between Cutouts - Based on Line Length)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/cutout_distance_between_cutouts(LineLengthBased).htm"},
{"name":"ディンプル間距離(Minimum Distance between Dimples)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/minimum_distance_between_dimples.htm"},
{"name":"ノッチ間の最小距離(Minimum Distance between Notches)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/minimum_notch_to_notch_distance.htm"},
{"name":"穿孔カットアウト間の最小距離(Minimum Distance between Perforated Cutouts)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Minimum_Distance_between_Perforated_Cutouts.htm"},
{"name":"長穴と曲げの最小平行距離(Minimum Distance from Bend to a Parallel Slot)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/min_dist_bend_to_parallel_slot.htm"},
{"name":"ディンプルと曲げ距離(Minimum Distance from Dimple to Bend)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/minimum_distance_from_dimple_to_bend.htm"},
{"name":"ディンプルとカットアウト距離(Minimum Distance from Dimple to Cutout)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/minimum_distance_from_dimple_to_cutout.htm"},
{"name":"ディンプルと穴距離(Minimum Distance from Dimple to Hole)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/minimum_distance_from_dimple_to_hole.htm"},
{"name":"ディンプルと部品エッジ距離(Minimum Distance from Dimple to Part Edge)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/minimum_distance_from_dimple_to_partedge.htm"},
{"name":"長穴とエッジの最小平行距離(Minimum Distance from Edge of Part to a Parallel Slot)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/min_dist_edge_to_parallel_slot.htm"},
{"name":"最小フランジ高さ(Minimum Flange Height)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/minimum_flange_height.htm"},
{"name":"最小穴径(Minimum Hole Diameter)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/minimum_hole_diameter.htm"},
{"name":"長穴の最小幅(Minimum Width of a Slot)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/min_width_of_slot.htm"},
{"name":"カットアウトの最小幅(Minimum Width of Cutout)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/minimum_width_of_cutout.htm"},
{"name":"同一方向の複数曲げ(Multiple Bends in Same Direction)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/multiple_bends_in_same_direction.htm"},
{"name":"ノッチ寸法(Notch Parameters)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/notch_parameters.htm"},
{"name":"ノッチと曲げの距離(Notch to Bend Distance)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/minimum_notch_to_bend_distance.htm"},
{"name":"ノッチ長さに基づくノッチと曲げの距離(Notch to Bend Distance - Based on Notch Length)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Notch_to_Bend_Distance_(Notch_Length_Based).htm"},
{"name":"オープンヘム(Open Hem)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/open_hem.htm"},
{"name":"パーツ削減(板厚ベース)(Part Count Reduction - Thickness Based)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/part_count_reduction_thickness_based.htm"},
{"name":"推奨板材サイズ(Preferred Sheet Sizes)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/preferred_sheet_sizes.htm"},
{"name":"推奨エンクロージャサイズ(Recommended Enclosure Size)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Recommended_Enclosure_size.htm"},
{"name":"推奨フランジ寸法(Recommended Flange Parameters)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/recommended_flange_parameters.htm"},
{"name":"推奨穴距離公差(Recommended Hole Distance Tolerance)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Recommended_Hole_Distance_Tolerance.htm"},
{"name":"推奨パンチ寸法(Recommended Punch Parameters)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Recommended_punch_parameters.htm"},
{"name":"推奨スプーン形状パラメータ(Recommended Spoon Parameters)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Recommended_Spoon_Parameters.htm"},
{"name":"リリーフと曲げの距離(Relief to Bend Distance)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Relief_To_Bend_Distance.htm"},
{"name":"ロールドヘム(Rolled Hem)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/curl_radius.htm"},
{"name":"ロールドヘムと穴エッジ距離(Rolled Hem to Hole Edge Distance)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/curl_to_hole_edge_spacing.htm"},
{"name":"板金モデリング推奨事項(Sheet Metal Modeling Practice)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Sheet_Metal_Modeling_Practice.htm"},
{"name":"ティアドロップヘム(Tear Drop Hem)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/tear_drop.htm"},
{"name":"共通曲げ半径の使用(Use Common Bend Radius)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Use_Common_Bend_Radius.htm"}];    
window.rh.model.publish(rh.consts('KEY_TEMP_DATA'), toc, { sync:true });    })();